### PR TITLE
update vulnerability

### PR DESCRIPTION
**Pull request by SONU74268**
update vulnerability

### CODE REVIEW

**Review by arshadkazmi42 — CHANGES_REQUESTED** [review]
Can you also delete yarn.lock file and update the PR

**Comment by SONU74268** [comment]
where i can find yarn.lock file.

**Comment by arshadkazmi42** [comment]
Seems that file is already deleted. never mind. this looks fine. merging

**Review by arshadkazmi42 — APPROVED** [review]
👍

**Comment by SONU74268** [comment]
thx for help. it was my first pull request. now i am ready to go. 
yup

**Comment by LukaMucak** [comment]
https://music.youtube.com/playlist?list=OLAK5uy_lu50Nj8dyA7DwzXT9uNnVi1DUNEfoSBOM&si=jYXmYbO_nnTEcjcR

**Pull request merged**
